version: '3'

tasks:
  h5p-convert:
    cmds:
      - rm -rf docs/left-side.h5p/
      - unzip input/left-side.h5p -d docs/left-side.h5p
      - rm -rf docs/right-side.h5p/
      - unzip input/right-side.h5p -d docs/right-side.h5p
      - rm -rf docs/device-compartment-1.h5p/
      - unzip input/device-compartment-1.h5p -d docs/device-compartment-1.h5p

  start:
    dir: docs
    deps:
      - h5p-convert
    cmds:
      - python3 -m http.server 8000
  
